[package]
name = "vit-servicing-station"
version = "0.1.0"
authors = ["danielsanchezq <daniel.sanchez@iohk.io>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = "1.13.2"
async-graphql-warp = "1.13.2"
async-trait = "0.1.33"
base64 = "0.12.1"
cfg-if = "0.1"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "1.4.4", features = ["sqlite", "r2d2"] }
dotenv = "0.9.0"
itertools = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.53"
structopt = "0.3.14"
thiserror = "1.0"
tokio = { version = "0.2.21", features = ["macros"] }
warp = { version = "0.2", features = ["tls"] }
diesel_migrations = "1.4.0"
#test dependencies

#diesel doesn't have an way to create empty db
#rustqlite is used for that purpose
rusqlite = "0.14"
tempfile = "3"
assert_fs = "1.0.0"
assert_cmd = "1.0.1"
[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["blocking"]

# This solves building on windows when sqlite3lib is not installed or missing in the `$PATH`
# as it happens with the github actions pipeline associated to this project.
[target.'cfg(windows)'.dependencies]
libsqlite3-sys =  { version = "0.9.1", features = ["bundled"] }

[features]
test-api = []

[dev-dependencies]
vit-servicing-station = {path= ".", features= ["test-api"] }


