name: API Check

on:
  pull_request:
    paths:
      - "doc/api/*.yaml"

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate with Spectral
        uses: stoplightio/spectral-action@v0.8.2
        with:
          file_glob: doc/api/*.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
